### ISSUE TITLE
Compiler crash in AnalyseDeclarationsTransform

### ISSUE THREAD

**Issue by pticon** [dofuuz/python-soxr#23]
Hello,

I am trying to build it from source and I am getting an error :

```
$ python3 setup.py bdist_wheel --verbose
Compiling src/soxr/cysoxr.pyx because it changed.
[1/1] Cythonizing src/soxr/cysoxr.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    def __dealloc__(self):
        csoxr.soxr_delete(self._soxr)

    @cython.boundscheck(False)
    @cython.wraparound(False)
    cpdef np.ndarray process(self, const datatype_t[:, ::1] x, bint last=False):
                                                   ^
------------------------------------------------------------

src/soxr/cysoxr.pyx:81:52: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 124, in analyse_declarations: ModuleNode(cysoxr.pyx:1:0,
    full_module_name = 'soxr.cysoxr')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(cysoxr.pyx:6:0)
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(cysoxr.pyx:48:5)
File 'Nodes.py', line 4814, in analyse_declarations: CClassDefNode(cysoxr.pyx:48:5,
    as_name = 'CySoxr',
    class_name = 'CySoxr',
    module_name = '',
    visibility = 'private')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(cysoxr.pyx:49:4)
File 'Nodes.py', line 375, in analyse_declarations: CompilerDirectivesNode(cysoxr.pyx:81:10)
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(cysoxr.pyx:81:10)
File 'Nodes.py', line 2359, in analyse_declarations: CFuncDefNode(cysoxr.pyx:81:10,
    decorators = [...]/0,
    is_c_class_method = 1,
    modifiers = [...]/0,
    overridable = 1,
    visibility = 'private')
File 'Nodes.py', line 681, in analyse: CFuncDeclaratorNode(cysoxr.pyx:81:28,
    calling_convention = '',
    overridable = 1)
File 'Nodes.py', line 891, in analyse: CArgDeclNode(cysoxr.pyx:81:35,
    is_generic = 1,
    outer_attrs = [...]/2)
File 'Nodes.py', line 1093, in analyse: MemoryViewSliceTypeNode(cysoxr.pyx:81:52,
    is_arg = True,
    name = 'memoryview')

Compiler crash traceback from this point on:
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 1093, in analyse
    self.type = PyrexTypes.MemoryViewSliceType(base_type, axes_specs)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/PyrexTypes.py", line 625, in __init__
    self.dtype_name = Buffer.mangle_dtype_name(self.dtype)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Buffer.py", line 631, in mangle_dtype_name
    return prefix + dtype.specialization_name()
  File "/usr/lib/python3/dist-packages/Cython/Compiler/PyrexTypes.py", line 57, in specialization_name
    common_subs = (self.empty_declaration_code()
  File "/usr/lib/python3/dist-packages/Cython/Compiler/PyrexTypes.py", line 51, in empty_declaration_code
    self._empty_declaration = self.declaration_code('')
  File "/usr/lib/python3/dist-packages/Cython/Compiler/PyrexTypes.py", line 1582, in declaration_code
    return self.const_base_type.declaration_code("const %s" % entity_code, for_display, dll_linkage, pyrex)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/PyrexTypes.py", line 1649, in declaration_code
    raise Exception("This may never happen, please report a bug")
Exception: This may never happen, please report a bug
Traceback (most recent call last):
  File "/home/pierre/Sources/python-soxr/setup.py", line 155, in <module>
    ext_modules=cythonize(extensions, language_level='3'),
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/soxr/cysoxr.pyx
```

Do you have any pointers to resolve it ?

**Comment by pticon** [comment]
It seems the **const** around **datatype_t** gives me the error.

After removing the **const**, I am still getting an error:
```
$ python3 setup.py build
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 35, in __getattr__
    return next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 419, in _parse_attr
    return getattr(StaticModule(module_name), attr_name)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 43, in __getattr__
    raise AttributeError(
AttributeError: soxr has no attribute __version__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/Sources/python-soxr/setup.py", line 153, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 804, in parse_config_files
    parse_configuration(
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 158, in parse_configuration
    meta.parse()
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 498, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 469, in parse_section
    self[name] = value
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 222, in __setitem__
    value = parser(value)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 599, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 422, in _parse_attr
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pierre/Sources/python-soxr/src/soxr/__init__.py", line 10, in <module>
    from . import cysoxr
ImportError: cannot import name 'cysoxr' from partially initialized module 'soxr' (most likely due to a circular import) (/home/pierre/Sources/python-soxr/src/soxr/__init__.py)
```

**Comment by dofuuz** [comment]
Do not execute setup.py directly. See BUILDING.md for build instruction.

(Upgrade Cython to >3.0 if you need setup.py for debugging.)

**Comment by pticon** [comment]
Thank you for the reply and it is indeed working with:
```shell
python -m build
```
